version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
    environment:
      JENKINS_OPTS: --httpPort=8080
    networks:
      jenkins-network:
        aliases: # Add alias to the jenkins network
          - jenkins
    depends_on:
      - docker

  git-client:
    image: alpine/git
    command: ["git", "clone", "https://github.com/NickName03/avs_rgz"]
    networks:
      - jenkins-network

  docker:
    image: docker:dind
    privileged: true
    networks:
      jenkins-network:
        aliases: # Add alias to the jenkins network
          - docker-daemon
    expose:
      - 2375

networks:
  jenkins-network:
    driver: bridge
volumes:
  jenkins_home:
