version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --httpPort=8080
    networks:
      - jenkins-network
    depends_on: #ensure that docker container is always up when jenkins is started
      - docker

  git-client:
    image: alpine/git
    command: ["git", "clone", "https://github.com/NickName03/avs_rgz"]
    networks:
      - jenkins-network

  docker:
    image: docker:dind
    privileged: true
    networks:
      - jenkins-network
    expose: #expose the docker port
      - 2375
networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home:
